const styles = {
  headerContainer: {
    display: ['inline', 'none'],
    position: 'sticky',
    top: 0,
    width: '100%',
    zIndex: 10,
  },
  topBanner: {
    zIndex: 2,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'space-between',
    bg: 'darkBlue',
    boxShadow: '0px 5px 10px 5px rgba(0,0,0,0.2)',
  },
  logo: {
    ml: '20px',
    height: '65px',
    width: '200px',
  },
  navIconContainer: {
    position: 'relative',
    height: '30px',
    width: '30px',
    mr: '20px',
  },
  navIcon: (bool) => ({
    position: 'absolute',
    height: '30px',
    width: '30px',
    cursor: 'pointer',
    opacity: bool ? 1 : 0,
    visibility: bool ? 'visible' : 'hidden',
    transition: 'all 0.25s ease-in-out',
  }),
  navContainer: (bool) => ({
    zIndex: 1,
    position: 'fixed',
    top: '65px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-between',
    py: '20px',
    bg: 'darkBlue',
    width: '100vw',
    opacity: bool ? 1 : 0,
    height: bool ? '100vh' : '0px',
    visibility: bool ? 'visible' : 'hidden',
    transition: 'all 0.25s ease-in-out',
  }),
  navItemsContainer: {
    height: '50%',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  navItems: (bool) => ({
    fontFamily: bool ? 'bold' : 'regular',
    fontSize: 4,
    color: 'white',
    textTransform: 'capitalize',
  }),
  divider: { width: '40px', color: 'white', my: '30px' },
  csmContainer: {
    flexDirection: 'column',
    alignItems: 'center',
    mb: '65px',
  },
  csmCircle: {
    height: '55px',
    width: '55px',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'white',
    borderRadius: 'circle',
  },
  csmTitle: {
    fontFamily: 'bold',
    fontSize: 4,
    fontWeight: 'bold',
    color: 'darkBlue',
    mb: '2px',
  },
  csmText: {
    fontSize: 1,
    color: 'background',
    textTransform: 'uppercase',
    mt: '10px',
    letterSpacing: '1px',
  },
};

export default styles;
