export default {
  menu: '/static/assets/images/menu_black.svg',
  close: '/static/assets/images/close_black.svg',
  couple: '/static/assets/images/couple_small.png',
  background: '/static/assets/images/background_small.png',
  arrowDown: '/static/assets/images/arrow_down.png',
  test: '/static/assets/images/test.png',
  icon_compass: '/static/assets/images/icon_compass.png',
  icon_warning: '/static/assets/images/icon_warning.png',
  desktop_0_Home: '/static/assets/images/desktop_0_Home.png',
  desktop_0_Home_back: '/static/assets/images/desktop_0_Home_back.png',
  desktop_2_Finca: '/static/assets/images/desktop_2_Finca.png',
  desktop_1_Gotis: '/static/assets/images/desktop_1_Gotis.png',
  desktop_1_Mancha_1: '/static/assets/images/desktop_1_Mancha_1.png',
  desktop_1_Mancha_2: '/static/assets/images/desktop_1_Mancha_2.png',
  desktop_1_Mancha_3: '/static/assets/images/desktop_1_Mancha_3.png',
  desktop_1_Mancha_4: '/static/assets/images/desktop_1_Mancha_4.png',
  desktop_1_Mancha_5: '/static/assets/images/desktop_1_Mancha_5.png',
  desktop_1_Mancha_6: '/static/assets/images/desktop_1_Mancha_6.png',
};
