export const buttons = {
  primary: {
    bg: 'blue',
    p: '8px 32px',
    fontSize: 0,
    fontWeight: 'bold',
    borderWidth: '2px',
    borderColor: 'blue',
    borderRadius: '0px',
    borderStyle: 'solid',
    letterSpacing: '2px',
    textTransform: 'uppercase',
    cursor: 'pointer',
    boxShadow: '3px 2px 7px 1px rgba(0,0,0,0.1)',
    '&:hover': {
      bg: ['blue', 'white'],
      color: ['white ', 'blue'],
    },
    '&:active': {
      bg: 'white',
      color: 'blue',
      boxShadow: 'inset 9px 5px 12px 2px rgba(0,0,0,0.1)',
    },
    '&:disabled': {
      bg: 'midGrey',
      color: 'white',
      border: 'none',
    },
  },
  secondary: {
    variant: 'buttons.primary',
    bg: 'white',
    color: 'blue',
    textDecoration: 'none',
    '&:hover': {
      bg: ['white', 'blue'],
      color: ['blue', 'white'],
      borderColor: ['blue', 'white'],
    },
    '&:active': {
      bg: 'blue',
      color: 'white',
      borderColor: 'white',
      boxShadow: 'inset 9px 5px 12px 2px rgba(0,0,0,0.1)',
    },
    '&:disabled': {
      bg: 'white',
      color: 'midGrey',
      borderColor: 'midGrey',
    },
  },
  submit: {
    variant: 'buttons.primary',
    fontSize: 2,
    my: '20px',
  },
  pageButtonSelected: {
    bg: 'blue',
    color: 'white',
    borderRadius: '50%',
    p: '12px 8px',
    mx: '10px',
    lineHeight: 0,
    border: 'transparent',
    fontSize: 2,
    fontWeight: 'bold',
    cursor: 'pointer',
    variant: 'buttons.primary',
  },
  pageButton: {
    variant: 'buttons.primary',
    bg: 'white',
    color: 'text',
    mx: '15px',
    lineHeight: 0,
    p: '0px',
    border: 'transparent',
    fontSize: 2,
    fontWeight: 'bold',
    cursor: 'pointer',
  },
  arrow: {
    variant: 'buttons.primary',
    bg: 'white',
    color: 'grey',
    p: '0px 20px',
    border: 'transparent',
    fontSize: 2,
    fontWeight: 'bold',
    cursor: 'pointer',
  },
  disabledArrow: {
    variant: 'buttons.primary',
    bg: 'white',
    color: 'lightGrey',
    p: '0px 20px',
    border: 'transparent',
    fontSize: 2,
    fontWeight: 'bold',
    cursor: 'pointer',
  },
  sendSelected: {
    variant: 'buttons.primary',
    bg: 'blue',
    fontSize: '1',
    borderRadius: '0px',
    p: '10px 25px',
    height: 'min-content',
    boxShadow: '9px 5px 15px 4px rgba(0,0,0,0.1)',
  },
  popup: {
    send: {
      bg: 'blue',
      borderRadius: '0px',
      fontSize: 1,
      letterSpacing: '2px',
      boxShadow: '9px 5px 15px 4px rgba(0,0,0,0.1)',
    },
    cancel: {
      border: '2px solid #0082ca',
      bg: 'white',
      color: 'blue',
      borderRadius: '0px',
      fontSize: 1,
      letterSpacing: '2px',
      ml: '20px',
      boxShadow: '9px 5px 15px 4px rgba(0,0,0,0.1)',
    },
  },
  back: {
    variant: 'buttons.secondary',
    width: 'max-content',
  },
};
